### ISSUE TITLE
Этот тип является менеджером записи регистра сведений

### ISSUE THREAD

**Issue by SeiOkami** [SeiOkami/CollectionMethodsOneS#25]
- [Метод в проекте](https://github.com/SeiOkami/CollectionMethodsOneS/blob/b75eb040b6c72224221d5bbfe16e59a5ae7cdc5a/%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D1%8F%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2/src/CommonModules/%D0%96%D0%A7_%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1%D0%A2%D0%B8%D0%BF%D0%B0%D0%BC%D0%B8/Module.bsl#L463C1-L484C13)
- [Тесты метода](https://github.com/SeiOkami/CollectionMethodsOneS/blob/b75eb040b6c72224221d5bbfe16e59a5ae7cdc5a/%D0%9A%D0%BE%D0%BB%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D1%8F%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2.%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5/src/CommonModules/%D0%96%D0%A7%D0%A2_%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1%D0%A2%D0%B8%D0%BF%D0%B0%D0%BC%D0%B8/Module.bsl#L659C1-L672C14)
- [Метод на FastCode](https://fastcode.im/Templates/7419)

**Текущая версия:**

```bsl
// Является ли переданный тип менеджером записи регистра сведений
// К сожалению, либо этот вариант, либо тупо проверка представления типа
// Источник: https://github.com/SeiOkami/CollectionMethodsOneS/issues/25
// 
// Параметры:
//  ТипЗначения - Тип
//
// Возвращаемое значение:
//   Булево
Функция ЭтоМенеджерЗаписиРегистраСведений(Знач ТипЗначения) Экспорт
    
    ОбъектМетаданных = Метаданные.НайтиПоТипу(ТипЗначения);
	Если ТипЗнч(ОбъектМетаданных) = Тип("ОбъектМетаданных") И Метаданные.РегистрыСведений.Содержит(ОбъектМетаданных) Тогда
		ТипМенеджераЗаписи = Тип("РегистрСведенийМенеджерЗаписи." + ОбъектМетаданных.Имя);
        ЭтоМенеджерЗаписи  = (ТипМенеджераЗаписи = ТипЗначения);
    Иначе
        ЭтоМенеджерЗаписи  = Ложь;
    КонецЕсли;
    
    Возврат ЭтоМенеджерЗаписи;
    
КонецФункции
```

**Comment by 1cnik-by** [comment]
Поправь КонецФункции**ъ**
